language: python
python:
  - "3.6"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - rm packages/unifi.yaml
  - rm packages/hue.yaml
install:
  - pip3 install homeassistant==${HA_VERSION}
script:
  - hass --script check_config -c . -f
