################################################################################
#  @author       :  Erin Reed (FireBall1725)
#  @date         :  26-Jul-2019
#  @package      :  Entry
#  @description  :  Automations and settings for the Entry
################################################################################

# Copyright 2020 Erin Reed / FireBall1725

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#  Sensors  ####################################################################
sensor:
  - platform: mqtt
    state_topic: "shellies/shellyht-58ED20/sensor/temperature"
    name: MQTT Entry Sensor Temperature
    unit_of_measurement: '°C'
    device_class: temperature

  - platform: mqtt
    state_topic: "shellies/shellyht-58ED20/sensor/humidity"
    name: MQTT Entry Sensor Humidity
    unit_of_measurement: '%'
    device_class: humidity

  - platform: mqtt
    state_topic: "shellies/shellyht-58ED20/sensor/battery"
    name: MQTT Entry Sensor Battery
    unit_of_measurement: '%'
    device_class: battery

#  Binary Sensors  #############################################################
binary_sensor:
  - platform: mqtt
    state_topic: "shellies/shellyht-58ED20/online"
    name: MQTT Entry Sensor Online
    device_class: connectivity

################################################################################
#  ToDo List:
#    - So many things to list
