################################################################################
#  @author       :  Erin Reed (FireBall1725)
#  @date         :  30-Jun-2019
#  @package      :  House Fan
#  @description  :  Automations for the whole house fan
################################################################################

# Copyright 2020 Erin Reed / FireBall1725

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#  Automations  ################################################################
automation:
  - alias: turn_on_house_fan
    trigger:
      - platform: state
        entity_id: group.house_fan_devices
        from: 'off'
        to: 'on'
        for:
          minutes: 1
    condition:
      - condition: numeric_state
        entity_id: sensor.dublin_apparent_temperature
        below: 24
    action:
      - service: switch.turn_on
        entity_id: switch.vera_house_fan

  - alias: turn_on_house_fan_temp_below
    trigger:
      - platform: numeric_state
        entity_id: sensor.dublin_apparent_temperature
        below: 24
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.vera_house_fan
          state: 'off'
        - condition: state
          entity_id: group.house_fan_devices
          state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.vera_house_fan

  - alias: turn_off_house_fan_temp_above
    trigger:
      - platform: numeric_state
        entity_id: sensor.dublin_apparent_temperature
        above: 24.1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.vera_house_fan
          state: 'on'
        - condition: state
          entity_id: group.house_fan_devices
          state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.vera_house_fan
      - service: tts.amazon_polly_say
        data_template:
          message: 'Attention! The outside temperature is higher than 24 degrees. turning off the house fan. Please close all windows and doors at your earliest convenience.'

  - alias: turn_off_house_fan_temp_below
    trigger:
      - platform: numeric_state
        entity_id: sensor.dublin_apparent_temperature
        below: 15.0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.vera_house_fan
          state: 'on'
        - condition: state
          entity_id: group.house_fan_devices
          state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.vera_house_fan

  - alias: turn_off_house_fan
    trigger:
      - platform: state
        entity_id: group.house_fan_devices
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.vera_house_fan

################################################################################
#  ToDo List:
#    - Fix the doors and windows so they all have to be closed to turn off the
#      house fan
