################################################################################
#  @author       :  Erin Reed (FireBall1725)
#  @date         :  23/06/2019
#  @package      :  Sally (Snake)
#  @description  :  Automations and settings for Sally's tank
################################################################################

# Copyright 2019 Erin Reed / FireBall1725

# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
# SOFTWARE.

#  Automations  ################################################################
automation:
  - alias: snake1_day
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: switch.turn_on
        entity_id: switch.template_snake1_daynight

  - alias: snake1_night
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: switch.turn_off
        entity_id: switch.template_snake1_daynight

  - alias: snake1_fog_on
    trigger:
      platform: numeric_state
      entity_id: sensor.template_snake1_avg_humidity
      below: 50
    action:
      service: switch.turn_on
      entity_id: switch.vera_snake1_plug2

  - alias: snake1_fog_off
    trigger:
      platform: numeric_state
      entity_id: sensor.template_snake1_avg_humidity
      above: 65
    action:
      service: switch.turn_off
      entity_id: switch.vera_snake1_plug2

#  Sensors  ####################################################################
sensor:
  - platform: template
    sensors:
      template_snake1_avg_humidity:
        value_template: '{{ ((float(states.sensor.esp32_snake1_left_humidity.state) + float(states.sensor.esp32_snake1_right_humidity.state)) / 2) | round(2) }}'
        unit_of_measurement: "%"
        icon_template: "mdi:water-percent"

      template_snake1_avg_temperature:
        value_template: '{{ ((float(states.sensor.esp32_snake1_left_temperature.state) + float(states.sensor.esp32_snake1_right_temperature.state)) / 2) | round(2) }}'
        unit_of_measurement: "°C"
        icon_template: "mdi:thermometer"

#  Switches  ###################################################################
switch:
  - platform: template
    switches:
      template_snake1_daynight:
        value_template: "{{ is_state('switch.vera_snake1_plug3', 'on') }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.vera_snake1_plug3
          - service: switch.turn_off
            data:
              entity_id: switch.vera_snake1_plug4
        turn_off:
          - service: switch.turn_on
            data:
              entity_id: switch.vera_snake1_plug4
          - service: switch.turn_off
            data:
              entity_id: switch.vera_snake1_plug3

#  Groups  #####################################################################
group:
  snake1_automations:
    name: Sally - Automations
    control: hidden
    entities:
      - script.snake1_day
      - script.snake1_night
      - switch.template_snake1_daynight
      - automation.snake1_day
      - automation.snake1_night

  snake1_controls:
    name: Sally - snake1_controls
    control: hidden
    entities:
      - switch.vera_snake1_plug1
      - switch.vera_snake1_plug2
      - switch.vera_snake1_plug3
      - switch.vera_snake1_plug4
      - switch.vera_snake1_plug5
      - switch.vera_snake1_usb1
      - switch.vera_snake1_usb2

#  Customize Entities  #########################################################
homeassistant:
  customize:
    script.snake1_day:
      icon: mdi:weather-sunny
      friendly_name: Snake 1 - Day Script
    
    script.snake1_night:
      icon: mdi:weather-night
      friendly_name: Snake 1 - Night Script
    
    switch.template_snake1_daynight:
      icon: mdi:theme-light-dark
      friendly_name: Snake 1 - Light State
    
    automation.snake1_day:
      icon: mdi:weather-sunny
      friendly_name: Snake 1 - Day Automation
    
    automation.snake1_night:
      icon: mdi:weather-night
      friendly_name: Snake 1 - Night Automation
    
    switch.vera_snake1_plug1:
      icon: mdi:radiator
    
    switch.vera_snake1_plug2:
      icon: mdi:water-percent
    
    switch.vera_snake1_plug3:
      icon: mdi:lightbulb
    
    switch.vera_snake1_plug4:
      icon: mdi:lightbulb
    
    switch.vera_snake1_plug5:
      icon: mdi:power-socket-us
    
    switch.vera_snake1_usb1:
      icon: mdi:usb
    
    switch.vera_snake1_usb2:
      icon: mdi:usb
    
    switch.vera_snake1_plugall:
      hidden: true

################################################################################
#  ToDo List:
#    - Add automations for humidifier
#    - Add alerts for water out on humidifier
